# mks_servo_can/mks_servo_can_library/mks_servo_can/constants.py
"""
Constants for the MKS Servo CAN library.
Includes CAN command codes, default values, and other relevant constants
derived from the MKS SERVO42D/57D_CAN User Manual.
"""

# Default CAN Interface Parameters
CAN_DEFAULT_BITRATE = 500000  # 500K bps
CAN_TIMEOUT_SECONDS = 1.0  # Default timeout for CAN operations

# CAN IDs
BROADCAST_ADDRESS = 0x00
DEFAULT_CAN_ID = 0x01

# Work Modes (from manual Part 3, section 2 and Part 5.2, command 0x82)
MODE_CR_OPEN = 0
MODE_CR_CLOSE = 1
MODE_CR_VFOC = 2
MODE_SR_OPEN = 3
MODE_SR_CLOSE = 4
MODE_SR_VFOC = 5  # Default for serial according to some examples

WORK_MODES = {
    MODE_CR_OPEN: "CR_OPEN (Pulse, Open loop)",
    MODE_CR_CLOSE: "CR_CLOSE (Pulse, Close loop)",
    MODE_CR_VFOC: "CR_VFOC (Pulse, FOC)",
    MODE_SR_OPEN: "SR_OPEN (Serial, Open loop)",
    MODE_SR_CLOSE: "SR_CLOSE (Serial, Close loop)",
    MODE_SR_VFOC: "SR_VFOC (Serial, FOC)",
}

# Command Codes (from manual Part 5 & 6)
# Read Status Parameters (Part 5.1)
CMD_READ_ENCODER_CARRY = 0x30
CMD_READ_ENCODER_ADDITION = 0x31
CMD_READ_MOTOR_SPEED_RPM = 0x32
CMD_READ_PULSES_RECEIVED = 0x33
CMD_READ_IO_STATUS = 0x34
CMD_READ_RAW_ENCODER_ADDITION = 0x35
CMD_READ_SHAFT_ANGLE_ERROR = 0x39
CMD_READ_EN_PIN_STATUS = 0x3A
CMD_READ_POWER_ON_ZERO_STATUS = 0x3B
CMD_RELEASE_STALL_PROTECTION = 0x3D
CMD_READ_MOTOR_PROTECTION_STATE = 0x3E

# Set System Parameters (Part 5.2)
CMD_CALIBRATE_ENCODER = 0x80
CMD_SET_WORK_MODE = 0x82
CMD_SET_WORKING_CURRENT = 0x83
CMD_SET_SUBDIVISION = 0x84
CMD_SET_EN_PIN_ACTIVE_LEVEL = 0x85
CMD_SET_MOTOR_DIRECTION = 0x86
CMD_SET_AUTO_SCREEN_OFF = 0x87
CMD_SET_STALL_PROTECTION = 0x88
CMD_SET_SUBDIVISION_INTERPOLATION = 0x89
CMD_SET_CAN_BITRATE = 0x8A
CMD_SET_CAN_ID = 0x8B
CMD_SET_SLAVE_RESPOND_ACTIVE = 0x8C
CMD_SET_GROUP_ID = 0x8D
CMD_SET_KEY_LOCK = 0x8F
CMD_SET_HOLDING_CURRENT_PERCENTAGE = 0x9B

# Write IO Port (Part 5.3)
CMD_WRITE_IO_PORT = 0x36

# Set Home Command (Part 5.4)
CMD_SET_HOME_PARAMETERS = 0x90
CMD_GO_HOME = 0x91
CMD_SET_CURRENT_AXIS_TO_ZERO = 0x92
CMD_SET_NOLIMIT_HOME_PARAMS = 0x94
CMD_SET_LIMIT_PORT_REMAP = 0x9E

# Set 0_Mode Command (Part 5.5)
CMD_SET_ZERO_MODE_PARAMETERS = 0x9A

# Restore Default Parameters (Part 5.6)
CMD_RESTORE_DEFAULT_PARAMETERS = 0x3F

# Restart Motor (Part 5.7)
CMD_RESTART_MOTOR = 0x41

# En Triggers and Position Error Protection (Part 5.8)
CMD_SET_EN_TRIGGER_POS_ERROR_PROTECTION = 0x9D

# Read System Parameter (Part 5.9)
CMD_READ_SYSTEM_PARAMETER_PREFIX = 0x00

# Run Motor Commands (Part 6)
# Query/Enable Motor (Part 6.2)
CMD_QUERY_MOTOR_STATUS = 0xF1
CMD_ENABLE_MOTOR = 0xF3

# Emergency Stop (Part 6.3)
CMD_EMERGENCY_STOP = 0xF7

# Speed Mode (Part 6.4)
CMD_RUN_SPEED_MODE = 0xF6
CMD_SAVE_CLEAN_SPEED_MODE_PARAMS = 0xFF # Command code for save/clean operations

# Data values for CMD_SAVE_CLEAN_SPEED_MODE_PARAMS
SPEED_MODE_PARAM_SAVE = 0xC8
SPEED_MODE_PARAM_CLEAN = 0xCA


# Position Mode 1: Relative motion by pulses (Part 6.5)
CMD_RUN_POSITION_MODE_RELATIVE_PULSES = 0xFD

# Position Mode 2: Absolute motion by pulses (Part 6.6)
CMD_RUN_POSITION_MODE_ABSOLUTE_PULSES = 0xFE

# Position Mode 3: Relative motion by axis (Part 6.7)
CMD_RUN_POSITION_MODE_RELATIVE_AXIS = 0xF4

# Position Mode 4: Absolute motion by axis (Part 6.8)
CMD_RUN_POSITION_MODE_ABSOLUTE_AXIS = 0xF5

CMD_SAVE_SPEED_PARAMS = 0xC8
CMD_CLEAN_SPEED_PARAMS = 0xCA
CMD_RUN_SPEED_MODE_SAVE_CLEAN_PARAMS = 0xFF


# Motor Types (for high-level API)
MOTOR_TYPE_SERVO42D = "MKS SERVO42D"
MOTOR_TYPE_SERVO57D = "MKS SERVO57D"
MOTOR_TYPE_SERVO28D = "MKS SERVO28D" # Mentioned in manual for Ma settings
MOTOR_TYPE_SERVO35D = "MKS SERVO35D" # Mentioned in manual for Ma settings


# Max currents (mA)
MAX_CURRENT_SERVO42D = 3000
MAX_CURRENT_SERVO57D = 5200
MAX_CURRENT_SERVO28D = 3000
MAX_CURRENT_SERVO35D = 3000

# Default RPMs and Speeds
MAX_RPM_OPEN_MODE = 400
MAX_RPM_CLOSE_MODE = 1500
MAX_RPM_VFOC_MODE = 3000

# Kinematics
DEFAULT_STEPS_PER_REVOLUTION = 200 * 16 # Example: 200 base steps, 16 microsteps
ENCODER_PULSES_PER_REVOLUTION = 0x4000  # 16384

# Response Status Codes
STATUS_SUCCESS = 0x01
STATUS_FAILURE = 0x00

# Calibration Status (for CMD_CALIBRATE_ENCODER 0x80)
STATUS_CALIBRATING = 0x00
STATUS_CALIBRATED_SUCCESS = 0x01 # Also used by other set commands as generic success
STATUS_CALIBRATING_FAIL = 0x02

# Slave Respond Active (for CMD_SET_SLAVE_RESPOND_ACTIVE 0x8C)
RESPOND_DISABLED = 0x00
RESPOND_ENABLED = 0x01
ACTIVE_DISABLED = 0x00  # Active data initiation disabled
ACTIVE_ENABLED = 0x01   # Active data initiation enabled

# Motor Status (for CMD_QUERY_MOTOR_STATUS 0xF1)
MOTOR_STATUS_QUERY_FAIL = 0x00
MOTOR_STATUS_STOPPED = 0x01
MOTOR_STATUS_SPEED_UP = 0x02
MOTOR_STATUS_SPEED_DOWN = 0x03
MOTOR_STATUS_FULL_SPEED = 0x04
MOTOR_STATUS_HOMING = 0x05
MOTOR_STATUS_CALIBRATING = 0x06 # Matches CALIBRATING status from 0x80

MOTOR_STATUS_MAP = {
    MOTOR_STATUS_QUERY_FAIL: "Query Fail",
    MOTOR_STATUS_STOPPED: "Stopped",
    MOTOR_STATUS_SPEED_UP: "Speeding Up",
    MOTOR_STATUS_SPEED_DOWN: "Slowing Down",
    MOTOR_STATUS_FULL_SPEED: "Full Speed",
    MOTOR_STATUS_HOMING: "Homing",
    MOTOR_STATUS_CALIBRATING: "Calibrating",
}

# Position Run Status (for run commands like 0xFD, 0xFE, 0xF4, 0xF5)
POS_RUN_FAIL = 0x00
POS_RUN_STARTING = 0x01
POS_RUN_COMPLETE = 0x02
POS_RUN_END_LIMIT_STOPPED = 0x03

# Home Status (for CMD_GO_HOME 0x91)
HOME_FAIL = 0x00
HOME_START = 0x01
HOME_SUCCESS = 0x02

# 0_Mode settings (for CMD_SET_ZERO_MODE_PARAMETERS 0x9A)
# Mode (byte2)
OMODE_DISABLE_AUTO_ZERO = 0
OMODE_DIR_MODE_AUTO_ZERO = 1
OMODE_NEAR_MODE_AUTO_ZERO = 2
# Set Zero Action (byte3)
OMODE_SET_ZERO_CLEAN = 0 # Clean previously set zero
OMODE_SET_ZERO_SET_CURRENT = 1 # Set current position as zero
OMODE_SET_ZERO_NO_MODIFY = 2 # Do not modify zero point
# Direction (byte5)
OMODE_DIR_CW = 0
OMODE_DIR_CCW = 1

# EN Pin active levels (for CMD_SET_EN_PIN_ACTIVE_LEVEL 0x85)
EN_ACTIVE_LOW = 0x00
EN_ACTIVE_HIGH = 0x01
EN_ACTIVE_ALWAYS = 0x02 # "Hold"

# Motor Direction (for CMD_SET_MOTOR_DIRECTION 0x86)
DIR_CW = 0x00
DIR_CCW = 0x01

# Bit rates for CMD_SET_CAN_BITRATE (0x8A)
CAN_BITRATE_125K = 0x00
CAN_BITRATE_250K = 0x01
CAN_BITRATE_500K = 0x02
CAN_BITRATE_1M = 0x03

# Simulator specific constants (can be kept here or moved if simulator becomes separate package)
SIM_DEFAULT_LATENCY_MS = 5
SIM_DEFAULT_MOTOR_RESPONSE_SCALE = 1.0